# Generated by Django 2.2.6 on 2019-10-01 19:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='Material Name')),
                ('part_number', models.CharField(max_length=100, verbose_name='Part No.')),
                ('unit_of_measure', models.CharField(max_length=10, verbose_name='UoM')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=100, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('FK_material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='materials.Material')),
            ],
        ),
    ]
