# Generated by Django 2.2.2 on 2019-10-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20191003_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='last_edited_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edited By'),
        ),
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
